name: Apex Forge Prime
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: APEX CORE INDUSTRIAL FORGE
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: stable
          python_version: 3.11
          buildozer_command: android debug
          repository_root: .

      - name: Upload APEX APK
        uses: actions/upload-artifact@v4
        with:
          name: Apex-Core-v600
          path: bin/*.apk
